#!/bin/bash

# ===============================
# MD5 checksum for filtered matrices
#
# INPUT ASSUMPTION:
# The current directory contains multiple sample folders like:
#   Folder_C1/
#   Folder_C2/
#   Folder_C3/
#
# Each sample must contain the following files generated by Cell Ranger:
#   sample_name/outs/filtered_feature_bc_matrix/
#   - barcodes.tsv.gz
#   - features.tsv.gz
#   - matrix.mtx.gz
# 
# Compute MD5s locally → write them into a new file (md5sums_filtered_matrix.txt)
# ===============================

OUTPUT="md5sums_filtered_matrix.txt"
> "$OUTPUT"

for sample in Folder_*; do
  echo "### Sample: $sample" >> "$OUTPUT"
  
  MATRIX_DIR="$sample/outs/filtered_feature_bc_matrix"
  
  for file in barcodes.tsv.gz features.tsv.gz matrix.mtx.gz; do
    if [[ -f "$MATRIX_DIR/$file" ]]; then
      md5sum "$MATRIX_DIR/$file" >> "$OUTPUT"
    else
      echo "Missing file: $MATRIX_DIR/$file" >> "$OUTPUT"
    fi
  done
  
  echo "" >> "$OUTPUT"
done

echo "MD5 checksum complete. Output: $OUTPUT"
